import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-center text-primary-600 font-title">Hello World</h1>
      <h2 className="text-center text-accent-400">Hi</h2>
    </div>
  );
};

export default Home;
